"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpenCheck, CalendarClock, CheckCircle2, Clock3, ExternalLink, HeartHandshake, MessageSquareText, Sprout, Target, UserRoundCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/components/auth/auth-provider";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/date";
import type { MentorshipAssignmentStatus, MentorshipMeetingMode, MentorshipPortal, MentorshipResourceAssignmentStatus, MentorshipSession } from "@/types/mentorship";

export default function MyMentorshipPage() {
  const { user } = useAuth();
  const client = useQueryClient();
  const [participantId, setParticipantId] = useState("");
  const [classroomId, setClassroomId] = useState("");
  const [classroomNote, setClassroomNote] = useState("");
  const [sessionAction, setSessionAction] = useState<{ type: "reschedule" | "feedback"; session: MentorshipSession }>();
  const [availability, setAvailability] = useState({ days: "", times: "", notes: "", meetingMode: "VIRTUAL" as MentorshipMeetingMode, hoursPerWeek: "" });
  const [reschedule, setReschedule] = useState({ scheduledStart: "", scheduledEnd: "", reason: "" });
  const [feedback, setFeedback] = useState({ rating: "5", comments: "", nextSteps: "" });
  const [serviceHourDialog, setServiceHourDialog] = useState(false);
  const [serviceHour, setServiceHour] = useState({ relationshipId: "", sessionId: "", serviceDate: "", hours: "", activity: "", description: "", evidenceUrl: "" });
  const [message, setMessage] = useState<string>();
  const [error, setError] = useState<string>();
  const portalQuery = useQuery({ queryKey: ["mentorship", "portal"], queryFn: () => api<MentorshipPortal>("/mentorship/portal"), enabled: Boolean(user) });
  const participants = portalQuery.data?.participants ?? [];
  const participant = participants.find((item) => item.id === participantId) ?? participants[0];
  const relationships = useMemo(() => participant?.relationships ?? [], [participant]);
  const classroom = relationships.find((relationship) => relationship.id === classroomId) ?? relationships[0];
  const sessions = classroom?.sessions.map((session) => ({ ...session, relationship: classroom })) ?? [];
  const goals = classroom?.goals ?? [];
  const resources = classroom?.resourceAssignments ?? [];
  const completedSessions = sessions.filter((session) => session.status === "COMPLETED");
  const upcomingSessions = sessions.filter((session) => session.status === "SCHEDULED" && new Date(session.scheduledEnd) >= new Date()).sort((a, b) => new Date(a.scheduledStart).getTime() - new Date(b.scheduledStart).getTime());
  const availabilityReady = participant ? hasMeaningfulValues(participant.application.availability) && Boolean(participant.application.meetingMode) : false;
  const selectedServiceRelationship = relationships.find((relationship) => relationship.id === serviceHour.relationshipId);
  const refresh = () => client.invalidateQueries({ queryKey: ["mentorship", "portal"] });
  const mutationOptions = { onSuccess: async () => { setError(undefined); await refresh(); }, onError: (caught: unknown) => setError(messageFrom(caught)) };
  const updateAvailability = useMutation({ mutationFn: (body: Record<string, unknown>) => api("/mentorship/portal/availability", { method: "PATCH", body: JSON.stringify(body) }), ...mutationOptions });
  const rescheduleSession = useMutation({ mutationFn: ({ id, body }: { id: string; body: Record<string, unknown> }) => api(`/mentorship/portal/sessions/${id}/reschedule`, { method: "POST", body: JSON.stringify(body) }), ...mutationOptions });
  const cancelSession = useMutation({ mutationFn: (id: string) => api(`/mentorship/portal/sessions/${id}/cancel`, { method: "POST", body: JSON.stringify({}) }), ...mutationOptions });
  const submitFeedback = useMutation({ mutationFn: ({ id, body }: { id: string; body: Record<string, unknown> }) => api(`/mentorship/portal/sessions/${id}/feedback`, { method: "POST", body: JSON.stringify(body) }), ...mutationOptions });
  const updateResource = useMutation({ mutationFn: ({ id, status }: { id: string; status: MentorshipResourceAssignmentStatus }) => api(`/mentorship/portal/resources/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }), ...mutationOptions });
  const updateAssignment = useMutation({ mutationFn: ({ id, status }: { id: string; status: MentorshipAssignmentStatus }) => api(`/mentorship/portal/assignments/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }), ...mutationOptions });
  const addNote = useMutation({ mutationFn: ({ relationshipId, body }: { relationshipId: string; body: string }) => api(`/mentorship/portal/relationships/${relationshipId}/notes`, { method: "POST", body: JSON.stringify({ body }) }), ...mutationOptions });
  const submitServiceHour = useMutation({ mutationFn: (body: Record<string, unknown>) => api("/mentorship/portal/service-hours", { method: "POST", body: JSON.stringify(body) }), ...mutationOptions });

  useEffect(() => {
    if (!participant) return;
    const value = participant.application.availability ?? {};
    setAvailability({ days: listValue(value.days), times: listValue(value.times), notes: typeof value.notes === "string" ? value.notes : "", meetingMode: participant.application.meetingMode ?? "VIRTUAL", hoursPerWeek: participant.application.hoursPerWeek?.toString() ?? "" });
  }, [participant]);

  useEffect(() => {
    if (!relationships.length) return;
    const requested = new URLSearchParams(window.location.search).get("classroom");
    setClassroomId((current) => relationships.some((relationship) => relationship.id === current) ? current : relationships.find((relationship) => relationship.id === requested)?.id ?? relationships[0].id);
  }, [relationships]);

  if (!user) return null;

  function saveAvailability(event: FormEvent) {
    event.preventDefault();
    if (!participant) return;
    updateAvailability.mutate({ participantId: participant.id, availability: { days: splitList(availability.days), times: splitList(availability.times), notes: availability.notes.trim() }, meetingMode: availability.meetingMode, hoursPerWeek: availability.hoursPerWeek ? Number(availability.hoursPerWeek) : undefined }, { onSuccess: () => setMessage("Availability updated.") });
  }

  function saveReschedule(event: FormEvent) {
    event.preventDefault();
    if (!sessionAction) return;
    rescheduleSession.mutate({ id: sessionAction.session.id, body: reschedule }, { onSuccess: () => { setSessionAction(undefined); setReschedule({ scheduledStart: "", scheduledEnd: "", reason: "" }); setMessage("Session rescheduled."); } });
  }

  function saveFeedback(event: FormEvent) {
    event.preventDefault();
    if (!sessionAction) return;
    submitFeedback.mutate({ id: sessionAction.session.id, body: { rating: Number(feedback.rating), comments: feedback.comments || undefined, nextSteps: feedback.nextSteps || undefined } }, { onSuccess: () => { setSessionAction(undefined); setFeedback({ rating: "5", comments: "", nextSteps: "" }); setMessage("Thank you. Your feedback was saved."); } });
  }

  function saveServiceHour(event: FormEvent) {
    event.preventDefault();
    if (!participant) return;
    submitServiceHour.mutate({ participantId: participant.id, relationshipId: serviceHour.relationshipId, sessionId: serviceHour.sessionId || undefined, serviceDate: serviceHour.serviceDate, minutes: Math.round(Number(serviceHour.hours) * 60), activity: serviceHour.activity, description: serviceHour.description || undefined, evidenceUrl: serviceHour.evidenceUrl || undefined }, { onSuccess: () => { setServiceHourDialog(false); setServiceHour({ relationshipId: "", sessionId: "", serviceDate: "", hours: "", activity: "", description: "", evidenceUrl: "" }); setMessage("Service hours submitted for administrative review."); } });
  }

  function saveClassroomNote(event: FormEvent) {
    event.preventDefault();
    if (!classroom || !classroomNote.trim()) return;
    addNote.mutate({ relationshipId: classroom.id, body: classroomNote.trim() }, { onSuccess: () => { setClassroomNote(""); setMessage("Classroom note shared."); } });
  }

  return <>
    <section className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#8a6556]">{new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date())}</p><h1 className="mt-2 font-serif text-4xl font-bold text-[#173c36]">Welcome back, {user.firstName} <span aria-hidden="true">👋🏾</span></h1><p className="mt-2 text-[var(--text-secondary)]">You’re in the right place. Let’s take today one step at a time.</p></div>
      <div className="flex items-center gap-3 rounded-2xl border border-[#eadca5] bg-[#fff5cf] px-4 py-3"><Sprout className="h-6 w-6 text-[#2f7464]" /><div><p className="text-[10px] font-bold uppercase tracking-wider text-[#8a6556]">Today’s reminder</p><p className="text-xs font-semibold text-[#173c36]">Questions are part of learning.</p></div></div>
    </section>
    {error ? <Card className="mb-5 border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card> : null}
    {message ? <Card className="mb-5 border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</Card> : null}
    {portalQuery.data?.notifications.some((notification) => !notification.readAt) ? <section className="mb-5 space-y-2" aria-label="Classroom notifications">{portalQuery.data.notifications.filter((notification) => !notification.readAt).slice(0, 3).map((notification) => <Card key={notification.id} className="border-[#eadca5] bg-[#fffaf0] p-4"><p className="font-semibold text-[#173c36]">{notification.title}</p><p className="mt-1 text-sm text-[var(--text-secondary)]">{notification.message}</p></Card>)}</section> : null}
    {participant ? <RoleOnboarding role={participant.role} availabilityReady={availabilityReady} relationshipReady={relationships.length > 0} sessionReady={upcomingSessions.length > 0 || completedSessions.length > 0} learningPlanReady={goals.length > 0 || resources.length > 0} /> : null}
    {participant && participant.role !== "MENTEE" ? <section className="mb-5"><Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-[var(--primary-blue)]" /><h2 className="font-semibold">Verified service hours</h2></div><p className="mt-1 text-sm text-[var(--text-secondary)]">Submit service time for administrator approval. Completed sessions do not count automatically.</p></div><Button type="button" disabled={!relationships.length} onClick={() => { setServiceHour({ relationshipId: relationships[0]?.id ?? "", sessionId: "", serviceDate: new Date().toISOString().slice(0, 10), hours: "", activity: "", description: "", evidenceUrl: "" }); setServiceHourDialog(true); }}>Submit hours</Button></div><div className="mt-4 flex flex-wrap gap-3"><Badge tone="green">{formatHours(participant.serviceHours.filter((entry) => entry.status === "APPROVED").reduce((sum, entry) => sum + entry.minutes, 0))} approved</Badge><Badge tone="gold">{participant.serviceHours.filter((entry) => entry.status === "SUBMITTED" || entry.status === "UNDER_REVIEW").length} awaiting review</Badge>{participant.stipendDecision ? <Badge tone={participant.stipendDecision.status === "ELIGIBLE" || participant.stipendDecision.status === "APPROVED" || participant.stipendDecision.status === "PAID" ? "green" : "gray"}>Stipend: {label(participant.stipendDecision.status)}</Badge> : null}</div>{participant.serviceHours.length ? <div className="mt-4 space-y-2">{participant.serviceHours.map((entry) => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md bg-slate-50 p-3 text-sm"><div><p className="font-medium">{entry.activity} · {formatHours(entry.minutes)}</p><p className="text-xs text-[var(--text-secondary)]">{formatDate(entry.serviceDate)}{entry.session ? ` · ${entry.session.title}` : ""}</p></div><Badge tone={entry.status === "APPROVED" ? "green" : entry.status === "REJECTED" ? "gray" : "gold"}>{label(entry.status)}</Badge></div>)}</div> : null}</Card></section> : null}
    {portalQuery.isLoading ? <Card className="p-8 text-center">Loading your mentorship portal…</Card> : portalQuery.isError ? <Card className="border-red-200 bg-red-50 p-6 text-center text-red-700">Your mentorship information could not be loaded.</Card> : !participant ? <Card className="border-dashed p-10 text-center"><HeartHandshake className="mx-auto h-10 w-10 text-[var(--primary-blue)]" /><h2 className="mt-4 text-lg font-semibold">No mentorship participation is linked yet</h2><p className="mx-auto mt-2 max-w-xl text-sm text-[var(--text-secondary)]">An administrator can invite you using the same email address as your approved mentor, tutor, or mentee application.</p></Card> : <div className="space-y-6">
      {participants.length > 1 ? <Card className="p-4"><Select value={participant.id} onChange={(event) => setParticipantId(event.target.value)}>{participants.map((item) => <option key={item.id} value={item.id}>{item.program.name} · {item.cohort.name} · {label(item.role)}</option>)}</Select></Card> : null}

      <Card className="overflow-hidden border-0 bg-[#214d45] text-white shadow-soft"><div className="grid gap-0 lg:grid-cols-[1fr_1.25fr]"><div className="relative min-h-48 overflow-hidden bg-[#d8e8de] p-7 text-[#173c36]"><div className="absolute -bottom-16 -left-10 h-44 w-[120%] rounded-[50%] bg-[#c6d9cd]" /><div className="absolute right-8 top-7 h-12 w-12 rounded-full bg-[#f4c85a]" /><div className="relative flex h-full flex-col justify-between"><p className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-[#587068]">{classroom ? `${label(classroom.counterpart.role)} classroom` : "My classroom"}</p><div><p className="font-serif text-2xl font-bold">{classroom?.counterpart.name ?? participant.program.name}</p><p className="mt-1 text-sm text-[#587068]">{participant.cohort.name}</p></div></div></div><div className="p-7 lg:p-9"><div className="flex flex-wrap items-center gap-2"><Badge tone="gold">{label(participant.role)}</Badge><Badge tone={participant.status === "ACTIVE" ? "green" : participant.status === "WAITLISTED" ? "gold" : "gray"}>{label(participant.status)}</Badge></div>{upcomingSessions[0] ? <><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.15em] text-[#bcd2ca]">Your next session</p><h2 className="mt-2 font-serif text-3xl font-bold">{upcomingSessions[0].title}</h2><p className="mt-2 text-sm text-[#c9d8d3]">{formatDateTime(upcomingSessions[0].scheduledStart)} · {label(upcomingSessions[0].meetingMode)}</p>{upcomingSessions[0].videoUrl ? <a href={upcomingSessions[0].videoUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex h-11 items-center gap-2 rounded-xl bg-[#f4c85a] px-5 text-sm font-bold text-[#173c36]"><ExternalLink className="h-4 w-4" /> Enter classroom</a> : null}</> : <><p className="mt-6 text-[10px] font-bold uppercase tracking-[0.15em] text-[#bcd2ca]">Your learning space</p><h2 className="mt-2 font-serif text-3xl font-bold">Ready when you are</h2><p className="mt-2 text-sm text-[#c9d8d3]">Your next session will appear here as soon as it is scheduled.</p></>}</div></div></Card>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={HeartHandshake} label="Relationships" value={relationships.length} /><Metric icon={CalendarClock} label="Upcoming sessions" value={upcomingSessions.length} /><Metric icon={CheckCircle2} label="Completed sessions" value={completedSessions.length} /><Metric icon={Target} label="Goals completed" value={goals.filter((goal) => goal.status === "COMPLETED").length} /></div>

      <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]">
        <section className="space-y-3"><h2 className="text-lg font-semibold">My classrooms</h2>{relationships.length ? relationships.map((relationship) => <Card key={relationship.id} className={`p-5 ${relationship.id === classroom?.id ? "ring-2 ring-[var(--primary-blue)]" : ""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{label(relationship.counterpart.role)}: {relationship.counterpart.name}</p><a className="text-sm text-[var(--primary-blue)] hover:underline" href={`mailto:${relationship.counterpart.email}`}>{relationship.counterpart.email}</a></div><div className="flex items-center gap-2"><Badge tone={relationship.status === "ACTIVE" ? "green" : "gold"}>{label(relationship.status)}</Badge><Button type="button" className="bg-slate-700 hover:bg-slate-600" onClick={() => setClassroomId(relationship.id)}>{relationship.id === classroom?.id ? "Open" : "View"}</Button></div></div><div className="mt-4 grid grid-cols-2 gap-3"><Progress label="Sessions" value={percentage(relationship.sessions.filter((session) => session.status === "COMPLETED").length, relationship.cohort.minimumSessions)} detail={`${relationship.sessions.filter((session) => session.status === "COMPLETED").length} / ${relationship.cohort.minimumSessions}`} /><Progress label="Hours" value={percentage(relationship.sessions.reduce((sum, session) => sum + (session.status === "COMPLETED" ? session.completedMinutes : 0), 0), relationship.cohort.expectedHours * 60)} detail={`${(relationship.sessions.reduce((sum, session) => sum + (session.status === "COMPLETED" ? session.completedMinutes : 0), 0) / 60).toFixed(1)} / ${relationship.cohort.expectedHours}`} /></div></Card>) : <Empty text="Your approved relationship will appear here after matching." />}</section>

        <section><h2 className="mb-3 text-lg font-semibold">My availability</h2><Card className="p-5"><form className="space-y-3" onSubmit={saveAvailability}><Input placeholder="Available days, comma separated" value={availability.days} onChange={(event) => setAvailability({ ...availability, days: event.target.value })} /><Input placeholder="Preferred times, comma separated" value={availability.times} onChange={(event) => setAvailability({ ...availability, times: event.target.value })} /><div className="grid grid-cols-2 gap-3"><Select value={availability.meetingMode} onChange={(event) => setAvailability({ ...availability, meetingMode: event.target.value as MentorshipMeetingMode })}><option value="VIRTUAL">Virtual</option><option value="IN_PERSON">In person</option><option value="HYBRID">Hybrid</option></Select><Input type="number" min="0" max="168" placeholder="Hours per week" value={availability.hoursPerWeek} onChange={(event) => setAvailability({ ...availability, hoursPerWeek: event.target.value })} /></div><Textarea placeholder="Availability notes" value={availability.notes} onChange={(event) => setAvailability({ ...availability, notes: event.target.value })} /><Button type="submit" disabled={updateAvailability.isPending}>{updateAvailability.isPending ? "Saving…" : "Save availability"}</Button></form></Card></section>
      </div>

      <section><h2 className="mb-3 text-lg font-semibold">Classroom resources</h2>{resources.length ? <div className="grid gap-3 lg:grid-cols-2">{resources.map((assignment) => { const canUpdate = assignment.assigneeParticipantId === participant.id; return <Card key={assignment.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4 text-[var(--primary-blue)]" /><p className="font-semibold">{assignment.resource?.title}</p></div>{assignment.resource?.description ? <p className="mt-2 text-sm text-[var(--text-secondary)]">{assignment.resource.description}</p> : null}</div><Badge tone={assignment.status === "COMPLETED" ? "green" : assignment.status === "IN_PROGRESS" ? "blue" : "gold"}>{label(assignment.status)}</Badge></div>{assignment.notes ? <p className="mt-3 rounded-md bg-slate-50 p-3 text-sm">{assignment.notes}</p> : null}<p className="mt-3 text-xs text-[var(--text-secondary)]">{assignment.goal ? `Goal: ${assignment.goal.title}` : assignment.session ? `Session: ${assignment.session.title}` : "General classroom resource"}{assignment.dueDate ? ` · Due ${formatDate(assignment.dueDate)}` : ""}{!canUpdate && assignment.assignee?.application ? ` · Assigned to ${assignment.assignee.application.firstName} ${assignment.assignee.application.lastName}` : ""}</p><div className="mt-3 flex flex-wrap gap-2">{assignment.resource?.url ? <a href={assignment.resource.url} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-md border border-[var(--border)] px-4 text-sm font-semibold"><ExternalLink className="h-4 w-4" /> Open resource</a> : null}<Select className="w-auto" value={assignment.status} disabled={!canUpdate || updateResource.isPending} aria-label={canUpdate ? `Update ${assignment.resource?.title ?? "resource"} progress` : `${assignment.resource?.title ?? "Resource"} progress is updated by the assignee`} onChange={(event) => updateResource.mutate({ id: assignment.id, status: event.target.value as MentorshipResourceAssignmentStatus }, { onSuccess: () => setMessage("Resource progress updated.") })}><option value="ASSIGNED">Assigned</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></Select></div></Card>; })}</div> : <Empty text="No learning resources have been assigned to this classroom yet." />}</section>

      <section><h2 className="mb-3 text-lg font-semibold">Assignments and follow-up tasks</h2>{classroom?.assignments.length ? <div className="space-y-3">{classroom.assignments.map((assignment) => <Card key={assignment.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{assignment.title}</p>{assignment.description ? <p className="mt-1 text-sm text-[var(--text-secondary)]">{assignment.description}</p> : null}<p className="mt-2 text-xs text-[var(--text-secondary)]">{assignment.dueDate ? `Due ${formatDate(assignment.dueDate)}` : "No due date"}{assignment.goal ? ` · Goal: ${assignment.goal.title}` : ""}{assignment.session ? ` · Session: ${assignment.session.title}` : ""}</p></div><Select className="w-auto" value={assignment.status} disabled={updateAssignment.isPending || assignment.status === "CANCELLED"} onChange={(event) => updateAssignment.mutate({ id: assignment.id, status: event.target.value as MentorshipAssignmentStatus }, { onSuccess: () => setMessage("Assignment progress updated.") })}><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option>{assignment.status === "CANCELLED" ? <option value="CANCELLED">Cancelled</option> : null}</Select></div></Card>)}</div> : <Empty text="No assignments or follow-up tasks are open in this classroom." />}</section>

      <section><h2 className="mb-3 text-lg font-semibold">Classroom notes</h2><Card className="p-5"><form className="flex flex-col gap-3 sm:flex-row" onSubmit={saveClassroomNote}><Textarea className="min-h-20 flex-1" placeholder="Share a note with this mentor, tutor, or mentee" value={classroomNote} onChange={(event) => setClassroomNote(event.target.value)} /><Button type="submit" disabled={!classroom || !classroomNote.trim() || addNote.isPending}>{addNote.isPending ? "Sharing…" : "Share note"}</Button></form>{classroom?.notes.length ? <div className="mt-5 space-y-3">{classroom.notes.map((note) => <div key={note.id} className="rounded-md bg-slate-50 p-3 text-sm"><p>{note.body}</p><p className="mt-2 text-xs text-[var(--text-secondary)]">{note.author.firstName} {note.author.lastName} · {formatDateTime(note.createdAt)}</p></div>)}</div> : <p className="mt-4 text-sm text-[var(--text-secondary)]">No shared notes in this classroom yet.</p>}</Card></section>

      <section><h2 className="mb-3 text-lg font-semibold">Upcoming sessions</h2>{upcomingSessions.length ? <div className="space-y-3">{upcomingSessions.map((session) => <Card key={session.id} className="p-4"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold">{session.title}</p><p className="mt-1 text-sm text-[var(--text-secondary)]">{formatDateTime(session.scheduledStart)} – {formatTime(session.scheduledEnd)} · {label(session.meetingMode)}</p><div className="mt-1 flex flex-wrap gap-3">{session.videoUrl ? <a className="text-sm text-[var(--primary-blue)] hover:underline" href={session.videoUrl} target="_blank" rel="noreferrer">Open meeting link</a> : session.location ? <p className="text-sm">{session.location}</p> : null}<a className="text-sm text-[var(--primary-blue)] hover:underline" href={calendarHref(session)} download={`${session.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.ics`}>Add to calendar</a></div></div><div className="flex gap-2"><Button type="button" className="bg-slate-700 hover:bg-slate-600" onClick={() => { setSessionAction({ type: "reschedule", session }); setReschedule({ scheduledStart: toLocalInput(session.scheduledStart), scheduledEnd: toLocalInput(session.scheduledEnd), reason: "" }); }}>Reschedule</Button><Button type="button" className="bg-red-700 hover:bg-red-600" disabled={cancelSession.isPending} onClick={() => { if (window.confirm("Cancel this mentorship session?")) cancelSession.mutate(session.id, { onSuccess: () => setMessage("Session cancelled.") }); }}>Cancel</Button></div></div></Card>)}</div> : <Empty text="No upcoming sessions are scheduled." />}</section>

      <section><h2 className="mb-3 text-lg font-semibold">Goals</h2>{goals.length ? <div className="grid gap-3 lg:grid-cols-2">{goals.map((goal) => <Card key={goal.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{goal.title}</p>{goal.description ? <p className="mt-1 text-sm text-[var(--text-secondary)]">{goal.description}</p> : null}</div><Badge tone={goal.status === "COMPLETED" ? "green" : goal.status === "IN_PROGRESS" ? "blue" : "gray"}>{label(goal.status)}</Badge></div><Progress label="Progress" value={goal.progressPercent} detail={`${goal.progressPercent}%`} /></Card>)}</div> : <Empty text="No goals have been recorded yet." />}</section>

      <section><h2 className="mb-3 text-lg font-semibold">Completed sessions & feedback</h2>{completedSessions.length ? <div className="space-y-3">{completedSessions.map((session) => <Card key={session.id} className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{session.title}</p><p className="text-sm text-[var(--text-secondary)]">{formatDateTime(session.scheduledStart)} · {session.completedMinutes} minutes</p></div><Button type="button" onClick={() => setSessionAction({ type: "feedback", session })}><MessageSquareText className="h-4 w-4" /> Give feedback</Button></div></Card>)}</div> : <Empty text="Completed sessions will appear here for feedback." />}</section>

      <section><h2 className="mb-3 text-lg font-semibold">Progress history</h2>{classroom?.progressUpdates.length ? <div className="space-y-3">{[...classroom.progressUpdates].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).map((update) => <Card key={update.id} className="p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{update.summary}</p>{update.progressRating ? <Badge tone="blue">{update.progressRating}/5</Badge> : null}</div>{update.challenges ? <p className="mt-2 text-sm">{update.challenges}</p> : null}{update.nextSteps ? <p className="mt-2 text-sm"><span className="text-[var(--text-secondary)]">Next steps: </span>{update.nextSteps}</p> : null}<p className="mt-2 text-xs text-[var(--text-secondary)]">{update.author.firstName} {update.author.lastName} · {formatDateTime(update.createdAt)}</p></Card>)}</div> : <Empty text="No progress updates have been recorded in this classroom." />}</section>
    </div>}

    <Dialog open={sessionAction?.type === "reschedule"} title="Reschedule session" description="Choose a new future date and time for this session." onClose={() => setSessionAction(undefined)}><form className="space-y-4" onSubmit={saveReschedule}><label className="text-sm text-[var(--text-secondary)]">New start<Input className="mt-1" type="datetime-local" value={reschedule.scheduledStart} onChange={(event) => setReschedule({ ...reschedule, scheduledStart: event.target.value })} required /></label><label className="text-sm text-[var(--text-secondary)]">New end<Input className="mt-1" type="datetime-local" value={reschedule.scheduledEnd} onChange={(event) => setReschedule({ ...reschedule, scheduledEnd: event.target.value })} required /></label><Textarea placeholder="Reason or note (optional)" value={reschedule.reason} onChange={(event) => setReschedule({ ...reschedule, reason: event.target.value })} /><Button type="submit" disabled={rescheduleSession.isPending}>{rescheduleSession.isPending ? "Saving…" : "Reschedule session"}</Button></form></Dialog>
    <Dialog open={sessionAction?.type === "feedback"} title="Session feedback" description={`Share feedback for ${sessionAction?.session.title ?? "this session"}.`} onClose={() => setSessionAction(undefined)}><form className="space-y-4" onSubmit={saveFeedback}><Select value={feedback.rating} onChange={(event) => setFeedback({ ...feedback, rating: event.target.value })}>{[5,4,3,2,1].map((rating) => <option key={rating} value={rating}>{rating} / 5</option>)}</Select><Textarea placeholder="What was helpful or challenging?" value={feedback.comments} onChange={(event) => setFeedback({ ...feedback, comments: event.target.value })} /><Textarea placeholder="Suggested next steps" value={feedback.nextSteps} onChange={(event) => setFeedback({ ...feedback, nextSteps: event.target.value })} /><Button type="submit" disabled={submitFeedback.isPending}>{submitFeedback.isPending ? "Saving…" : "Submit feedback"}</Button></form></Dialog>
    <Dialog open={serviceHourDialog} title="Submit service hours" description="These hours will remain pending until an administrator verifies them." onClose={() => setServiceHourDialog(false)}><form className="space-y-4" onSubmit={saveServiceHour}><Select value={serviceHour.relationshipId} onChange={(event) => setServiceHour({ ...serviceHour, relationshipId: event.target.value, sessionId: "" })} required><option value="">Select relationship</option>{relationships.map((relationship) => <option key={relationship.id} value={relationship.id}>{relationship.counterpart.name} · {relationship.cohort.name}</option>)}</Select><Select value={serviceHour.sessionId} onChange={(event) => setServiceHour({ ...serviceHour, sessionId: event.target.value })}><option value="">Service not tied to one session</option>{selectedServiceRelationship?.sessions.filter((session) => session.status === "COMPLETED").map((session) => <option key={session.id} value={session.id}>{session.title} · {formatDate(session.scheduledStart)}</option>)}</Select><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-[var(--text-secondary)]">Service date<Input className="mt-1" type="date" max={new Date().toISOString().slice(0, 10)} value={serviceHour.serviceDate} onChange={(event) => setServiceHour({ ...serviceHour, serviceDate: event.target.value })} required /></label><label className="text-sm text-[var(--text-secondary)]">Hours<Input className="mt-1" type="number" min="0.25" max="24" step="0.25" value={serviceHour.hours} onChange={(event) => setServiceHour({ ...serviceHour, hours: event.target.value })} required /></label></div><Input placeholder="Service activity" value={serviceHour.activity} onChange={(event) => setServiceHour({ ...serviceHour, activity: event.target.value })} required /><Textarea placeholder="What work was completed?" value={serviceHour.description} onChange={(event) => setServiceHour({ ...serviceHour, description: event.target.value })} /><Input type="url" placeholder="Evidence link (optional)" value={serviceHour.evidenceUrl} onChange={(event) => setServiceHour({ ...serviceHour, evidenceUrl: event.target.value })} /><Button type="submit" disabled={submitServiceHour.isPending}>{submitServiceHour.isPending ? "Submitting…" : "Submit for review"}</Button></form></Dialog>
  </>;
}

function Metric({ icon: Icon, label: text, value }: { icon: typeof UserRoundCheck; label: string; value: number }) { return <Card className="p-4"><Icon className="h-5 w-5 text-[var(--primary-blue)]" /><p className="mt-3 text-xs font-semibold uppercase text-[var(--text-secondary)]">{text}</p><p className="mt-1 text-2xl font-bold">{value}</p></Card>; }
function RoleOnboarding({ role, availabilityReady, relationshipReady, sessionReady, learningPlanReady }: { role: "MENTOR" | "TUTOR" | "MENTEE"; availabilityReady: boolean; relationshipReady: boolean; sessionReady: boolean; learningPlanReady: boolean }) {
  const content = role === "MENTOR"
    ? { title: "Start strong as a mentor", description: "Build trust first, then turn the mentee’s goals into a practical plan.", relationship: "Meet your mentee", final: "Schedule the first mentoring session", finalReady: sessionReady }
    : role === "TUTOR"
      ? { title: "Set up your tutoring classroom", description: "Understand the learner’s needs and prepare a calm, focused first lesson.", relationship: "Meet your learner", final: "Prepare the first tutoring session", finalReady: sessionReady }
      : { title: "Make this classroom yours", description: "Tell your support team when you are available and what you want to accomplish.", relationship: "Meet your mentor or tutor", final: "Review your learning plan", finalReady: learningPlanReady };
  const tasks = [
    { label: "Confirm your availability and meeting preference", done: availabilityReady },
    { label: content.relationship, done: relationshipReady },
    { label: content.final, done: content.finalReady }
  ];
  const completed = tasks.filter((task) => task.done).length;
  return <Card className="mb-5 overflow-hidden border-[#d8e8de] p-0"><div className="grid lg:grid-cols-[0.8fr_1.2fr]"><div className="bg-[#d8e8de] p-6 text-[#173c36]"><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#587068]">{label(role)} onboarding</p><h2 className="mt-2 font-serif text-2xl font-bold">{content.title}</h2><p className="mt-2 text-sm leading-6 text-[#587068]">{content.description}</p><p className="mt-5 text-sm font-bold">{completed} of {tasks.length} ready</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/70"><div className="h-full rounded-full bg-[#2f7464] transition-all" style={{ width: `${Math.round((completed / tasks.length) * 100)}%` }} /></div></div><div className="space-y-3 p-6">{tasks.map((task, index) => <div key={task.label} className="flex items-center gap-3 rounded-xl border border-[var(--border)] bg-white p-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-sm font-bold ${task.done ? "bg-emerald-100 text-emerald-700" : "bg-[#fff5cf] text-[#8a6556]"}`}>{task.done ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</span><div><p className="text-sm font-semibold">{task.label}</p><p className="text-xs text-[var(--text-secondary)]">{task.done ? "Ready" : "Still to do"}</p></div></div>)}</div></div></Card>;
}
function Progress({ label: text, value, detail }: { label: string; value: number; detail: string }) { return <div className="mt-3"><div className="flex justify-between text-xs"><span className="text-[var(--text-secondary)]">{text}</span><span className="font-semibold">{detail}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-[var(--primary-blue)]" style={{ width: `${Math.min(100, value)}%` }} /></div></div>; }
function Empty({ text }: { text: string }) { return <Card className="border-dashed p-6 text-center text-sm text-[var(--text-secondary)]">{text}</Card>; }
function formatHours(minutes: number) { return `${Math.round(minutes / 6) / 10} hr${minutes === 60 ? "" : "s"}`; }
function percentage(value: number, target: number) { return target ? Math.round((value / target) * 100) : value ? 100 : 0; }
function splitList(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function listValue(value: unknown) { return Array.isArray(value) ? value.join(", ") : typeof value === "string" ? value : ""; }
function hasMeaningfulValues(value: Record<string, unknown>) { return Object.values(value ?? {}).some((entry) => Array.isArray(entry) ? entry.length > 0 : typeof entry === "string" ? entry.trim().length > 0 : Boolean(entry)); }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/(^|\s)\S/g, (letter) => letter.toUpperCase()); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function formatTime(value: string) { return new Intl.DateTimeFormat("en-US", { timeStyle: "short" }).format(new Date(value)); }
function toLocalInput(value: string) { const date = new Date(value); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0, 16); }
function calendarHref(session: MentorshipSession) { const compact = (value: string) => new Date(value).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, ""); const escape = (value: string) => value.replaceAll("\\", "\\\\").replaceAll(",", "\\,").replaceAll(";", "\\;").replaceAll("\n", "\\n"); const content = ["BEGIN:VCALENDAR", "VERSION:2.0", "PRODID:-//Pilye//Classroom//EN", "BEGIN:VEVENT", `UID:${session.id}@pilye`, `DTSTAMP:${compact(new Date().toISOString())}`, `DTSTART:${compact(session.scheduledStart)}`, `DTEND:${compact(session.scheduledEnd)}`, `SUMMARY:${escape(session.title)}`, session.videoUrl ? `URL:${session.videoUrl}` : session.location ? `LOCATION:${escape(session.location)}` : "", session.agenda ? `DESCRIPTION:${escape(session.agenda)}` : "", "END:VEVENT", "END:VCALENDAR"].filter(Boolean).join("\r\n"); return `data:text/calendar;charset=utf-8,${encodeURIComponent(content)}`; }
function messageFrom(value: unknown) { if (!(value instanceof Error)) return "The request could not be completed."; try { const parsed = JSON.parse(value.message) as { message?: string | string[] }; return Array.isArray(parsed.message) ? parsed.message.join(" ") : parsed.message ?? value.message; } catch { return value.message; } }
